name: ci #nome. Poderia ser qualquer 1

on: # o pipeline ser치 disparado quando houver um push para o branch main ou quando houver um PR
  push:
    branches:
      - main
  pull_request:

jobs: # baixa as dependencias do lint
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install -g --unsafe-perm=true eslint
    - name: Run ESLint
      run: npm run lint
  cypress-tests-desktop:
    needs: eslint # precisa que o job anterior eslint tenha passado
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout #baixa o c칩digo do workspace para o pipeline
        uses: actions/checkout@v2 # imagem do Cypress

      - name: Run end-to-end tests on desktop viewport 游빍
        uses: cypress-io/github-action@v2
        env:
        # vari치veis de ambiente a seguir
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.GITHUB_TOKEN }
        with:
          record: true
          command: cypress run --record # o job executar치 o script npm test
  cypress-tests-tablet:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run end-to-end tests on tablet viewport 游빍
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
        with:
          command: npm run test:tablet